### ISSUE TITLE
[BUG] Plenary unable to open compile swap file on Windows

### ISSUE THREAD

**Issue by samwdp** [ej-shafran/compile-mode.nvim#41] opened 2024-10-17 22:04 UTC
### Existing Issues

- [X] I have searched the existing issues

### Describe the bug

When running compile for the first time the error ```Error executing Lua callback: .../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: .../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: vim/_editor.lua:431: nvim_exec2(): Vim(sbuffer):E303: Unable to open swap file for "*compilation*", recovery impossible```

![image](https://github.com/user-attachments/assets/f2fa2b33-3521-4035-b6ee-ee2ab5331515)

Then when the \*compilation\* buffer is open and a Compile or Recompile command is run the output is correct
![image](https://github.com/user-attachments/assets/ca065a48-06f3-47bf-96de-171d2d1ecf03)

I have already set my nvim directory by doing vim.opt.directory = "my_location" in my init.lua. I can see swap files created in there for the buffers I have open. 
I have no other issues with plugins that use Plenary

### Steps To Reproduce

```markdown
1. nvim on Windows
2. run Compile 1 time, you get an error then the compilation buffer is open
3. With an already open compilation buffer, run the compile command again or recompile
4. Close down the compilation buffer and then return to step 3
```

### Expected Behavior

Complation buffer opens and output is shown

### Neovim Version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Plugin Version

```markdown
nightly version as of 17/10/2024 21:58 UTC
```

### Configuration

```
return {
    "ej-shafran/compile-mode.nvim",
    -- you can just use the latest version:
    branch = "nightly",
    -- or the most up-to-date updates:
    -- branch = "nightly",
    dependencies = {
        "nvim-lua/plenary.nvim",
        -- if you want to enable coloring of ANSI escape codes in
        -- compilation output, add:
        { "m00qek/baleia.nvim", tag = "v1.3.0" },
    },
    config = function()
        ---@type CompileModeOpts
        vim.g.compile_mode = {
            -- to add ANSI escape code support, add:
            baleia_setup = true,
        }
    end
}
```

### Additional Context

```markdown
compile-mode: require("compile-mode.health").check()

compile-mode.nvim report ~
- OK everything checks out
```

**Comment by samwdp** [comment] 2024-10-18 21:14
After a bit more digging, I have found that changing the buffer name to a name without any asterisks in it stops this error. Not sure why this is so having the following config surpresses this error
```lua
return {
    "ej-shafran/compile-mode.nvim",
    -- you can just use the latest version:
    branch = "nightly",
    -- or the most up-to-date updates:
    -- branch = "nightly",
    dependencies = {
        "nvim-lua/plenary.nvim",
        -- if you want to enable coloring of ANSI escape codes in
        -- compilation output, add:
        { "m00qek/baleia.nvim", tag = "v1.3.0" },
    },
    config = function()
        ---@type CompileModeOpts
        vim.g.compile_mode = {
            buffer_name="compilation",
            -- to add ANSI escape code support, add:
            baleia_setup = true,
        }
    end
}
```

**Comment by ej-shafran** [comment] 2024-10-19 22:31
Interesting. We've had issues with the asterisks in the buffer name in the past on Windows, but I believed I had fixed them (also, the Windows tests don't seem to show this issue). I'll try to give this a look.

**Comment by ej-shafran** [comment] 2024-10-21 00:00
Can't seem to reproduce this error in the tests. Mind creating a reproduction in a container or something of the sort? Seems like the issue is pretty dang specific...

**Comment by ej-shafran** [comment] 2024-10-30 11:35
Since I can't reproduce this in the tests using your provided Neovim version on Windows (https://github.com/ej-shafran/compile-mode.nvim/actions/runs/11592311762/job/32273912262?pr=45), I'm closing this issue. If this problem keeps popping up or someone can create a reproduction, I'll reopen.

**Closed by ej-shafran** 2024-10-30 11:35 UTC
Labels: bug

**Comment by sebastian-j-ibanez** [comment] 2025-07-08 18:42
This is the output of `:set directory?`:
`directory=~\AppData\Local\nvim-data\swap\\`

It is a valid location, I see other swap files there.

I will give that issue a read, thanks.

**Comment by sebastian-j-ibanez** [comment] 2025-07-08 18:52
The previous fix by setting `buffer_name="compilation"` got rid of the error message, but there is no additional output after printing the compile command in the new buffer.

@samwdp have you experienced this as well?

**Comment by PrescientSentinel** [comment] 2025-08-24 18:16
I had this issue too. @ej-shafran, the reason it didn't show up in the tests is because the test config sets the global option of 'noswapfile'. When I remove that I get failed tests on Windows because of this bug.

It happens because of Windows not being able to have '*' in a filename, in addition to buffer options not being set until after the new buffer is loaded, and then nvim tries to create a swapfile which errors. I've got a fix for it and can submit a PR if you like.
